const fs=require('fs'); const path=require('path'); const {clampText,normalizeText}=require('../utils');
function parseJson(raw){const c=String(raw||'').replace(/^```(?:json)?/i,'').replace(/```$/i,'').trim(); try{return JSON.parse(c)}catch{const s=c.indexOf('['),e=c.lastIndexOf(']');if(s>=0&&e>s)return JSON.parse(c.slice(s,e+1));throw new Error('LLM returned invalid JSON');}}
class DigestGenerator{
  constructor(config,clodex){this.config=config;this.clodex=clodex;this.promptTemplate=fs.readFileSync(path.join(__dirname,'../../prompts/digest_prompt.txt'),'utf8');this.calls=0;}
  scoreRussia(item){const text=normalizeText(`${item.title} ${item.description||''}`);return(this.config.digest.keywords||[]).reduce((s,k)=>text.includes(normalizeText(k))?s+1:s,0);}
  fallback(items){const cfg=this.config.digest;const sorted=[...items].sort((a,b)=>this.scoreRussia(b)-this.scoreRussia(a)||new Date(b.publishedAt)-new Date(a.publishedAt));const chosen=[];for(const x of sorted.filter(x=>this.scoreRussia(x)>0).slice(0,cfg.russia_focused))chosen.push({type:'russia',item:x,title:x.title,summary:x.description||''});const used=new Set(chosen.map(x=>x.item.url));const intl=sorted.find(x=>!used.has(x.url)&&this.scoreRussia(x)===0)||sorted.find(x=>!used.has(x.url));if(intl&&chosen.length<cfg.items_count)chosen.push({type:'international',item:intl,title:intl.title,summary:intl.description||''});return chosen.slice(0,cfg.items_count);}
  async generateOne(item,type='russia'){if(!this.clodex||this.calls>=(this.config.digest.max_llm_calls_per_run||8))return{type,item,title:item.title,summary:item.description||''};try{this.calls++;const raw=await this.clodex.chat([{role:'system',content:'Отвечай строго JSON без markdown.'},{role:'user',content:`Сделай одну карточку новости на русском. Тип: ${type}. Не выдумывай факты. Верни JSON {"title":"...","summary":"..."}.\n${JSON.stringify({title:item.title,description:clampText(item.description,this.config.digest.max_input_chars_per_item||2200),source:item.source,publishedAt:item.publishedAt})}`}]);const o=parseJson(raw);return{type,item,title:String(o.title||item.title).trim(),summary:String(o.summary||item.description||'').trim()};}catch(e){console.error(`[CLODEX per-item] ${e.message}`);return{type,item,title:item.title,summary:item.description||''};}}
  async generate(items){this.calls=0;const cfg=this.config.digest,candidates=items.slice(0,cfg.max_candidates_for_llm||20);if(!candidates.length)throw new Error('No news candidates available');if(!this.clodex)return this.fallback(candidates);const materials=candidates.map((x,i)=>({index:i,title:clampText(x.title,300),description:clampText(x.description,cfg.max_input_chars_per_item||2200),source:x.source,publishedAt:x.publishedAt,url:x.url}));const prompt=this.promptTemplate.replace('{RUSSIA_COUNT}',String(cfg.russia_focused)).replace('{INTERNATIONAL_COUNT}',String(cfg.international)).replace('{KEYWORDS}',(cfg.keywords||[]).join(', ')).replace('{EXCLUDE_KEYWORDS}',(cfg.exclude_keywords||[]).join(', '))+`\n\nМатериалы:\n${JSON.stringify(materials,null,2)}`;try{this.calls++;const raw=await this.clodex.chat([{role:'system',content:'Отвечай строго по правилам и в требуемом JSON формате.'},{role:'user',content:prompt}]);const selected=parseJson(raw).filter(x=>x&&x.selected!==false&&Number.isInteger(x.source_index));const result=selected.map(x=>{const item=candidates[x.source_index];return item?{type:x.type==='international'?'international':'russia',item,title:String(x.title||item.title).trim(),summary:String(x.summary||item.description||'').trim()}:null;}).filter(Boolean);const combined=[...result.filter(x=>x.type==='russia').slice(0,cfg.russia_focused),...result.filter(x=>x.type==='international').slice(0,cfg.international)];if(combined.length<cfg.items_count){const fallback=this.fallback(candidates),have=new Set(combined.map(x=>x.item.url));for(const x of fallback){if(combined.length>=cfg.items_count)break;if(!have.has(x.item.url))combined.push(x);}}return combined.slice(0,cfg.items_count);}catch(e){console.error(`[CLODEX] ${e.message}; switching to per-item fallback`);const fallback=this.fallback(candidates),refined=[];for(const e of fallback){if(refined.length>=cfg.items_count)break;refined.push(await this.generateOne(e.item,e.type));}return refined;}}
}
module.exports=DigestGenerator;
