const axios = require('axios');
const Parser = require('rss-parser');
const {getByPath,validHttpUrl,normalizeText,dedupeBySimilarity,sleep}=require('../utils');
class NewsFetcher {
  constructor(config, tracker){ this.config=config; this.tracker=tracker; this.parser=new Parser({timeout:15000}); }
  async withRetry(fn, attempts=3, baseMs=700){ let last; for(let i=1;i<=attempts;i++){try{return await fn();}catch(e){last=e;if(i<attempts)await sleep(baseMs*2**(i-1));}} throw last; }
  isAllowed(a){ const text=normalizeText(`${a.title} ${a.description||''}`); const excluded=(this.config.digest.exclude_keywords||[]).some(k=>text.includes(normalizeText(k))); return !excluded&&!!a.title&&validHttpUrl(a.url); }
  normalize(item,source,extra={}){ return {title:String(item.title||'').trim(),description:String(item.description||item.contentSnippet||'').replace(/<[^>]*>/g,' ').trim(),url:item.url||item.link||'',publishedAt:item.publishedAt||item.isoDate||item.pubDate||new Date().toISOString(),source:item.source||source||'unknown',...extra}; }
  async fetchRss(){ const feeds=this.config.news_sources.rss_feeds||[]; const out=[]; for(const url of feeds){try{const feed=await this.withRetry(()=>this.parser.parseURL(url)); for(const item of feed.items||[]){const n=this.normalize(item,feed.title||url,{sourceType:'rss'}); if(this.isAllowed(n))out.push(n);}}catch(e){console.error(`[RSS] ${url}: ${e.message}`);}} return out; }
  providerList(){ const ns=this.config.news_sources||{}; const fl=this.config.monitoring?.free_limits||{}; const list=[]; const seen=new Set(); for(const p of ['newsapi','gnews','mediastack']){const cfg=ns[p]; if(cfg&&cfg.enabled!==false){const merged={...cfg,provider:p}; if(!merged.api_key||String(merged.api_key).startsWith('YOUR_')){const alt=fl[p]?.api_key; if(alt&&!String(alt).startsWith('YOUR_'))merged.api_key=alt;} list.push(merged); seen.add(p);} } const legacy=ns.news_api; if(legacy&&legacy.enabled){const p=String(legacy.provider||'newsapi').toLowerCase(); if(!seen.has(p))list.push({...legacy,provider:p}); } return list; }
 async fetchNewsApi(){ const out=[]; for(const cfg of this.providerList()){ if(!cfg.api_key||String(cfg.api_key).startsWith('YOUR_'))continue; try{ out.push(...await this.fetchProvider(cfg)); }catch(e){console.error(`[NEWS API:${cfg.provider}] ${e.message}`);} } return out; }
 async fetchProvider(cfg){ const p=String(cfg.provider||'newsapi').toLowerCase(); const endpoint=cfg.endpoint||({newsapi:'https://newsapi.org/v2/top-headlines',gnews:'https://gnews.io/api/v4/top-headlines',mediastack:'https://api.mediastack.com/v1/news'}[p]); if(!endpoint)return []; const cats=cfg.categories?.length?cfg.categories:[null]; const out=[]; for(const category of cats){const params={}; if(p==='newsapi'){params.apiKey=cfg.api_key;params.language=cfg.language||'ru';params.country=cfg.country||'ru';params.pageSize=cfg.page_size||30;if(category)params.category=category;} else if(p==='gnews'){params.apikey=cfg.api_key;params.lang=cfg.language||'ru';params.max=cfg.page_size||10;if(cfg.country)params.country=cfg.country;if(category)params.topic=category;} else {params.access_key=cfg.api_key;params.languages=cfg.language||'ru';params.limit=cfg.page_size||30;if(category)params.categories=category;} try{const r=await this.withRetry(()=>axios.get(endpoint,{params,timeout:20000})); if(this.tracker)this.tracker.trackHttp(p,`news.fetch.${category||'all'}`); const body=r.data||{}; const items=body.articles||body.results||body.data||[]; out.push(...items.map(x=>this.normalize({title:x.title,description:x.description||x.summary,url:x.url||x.link,publishedAt:x.publishedAt||x.published_at,source:typeof x.source==='string'?x.source:x.source?.name},p,{sourceType:p,category})).filter(x=>this.isAllowed(x)));}catch(e){console.error(`[NEWS API:${p}:${category||'all'}] ${e.message}`);}} return out; }
  async fetchCustom(){ const sources=this.config.news_sources.custom||[]; const out=[]; for(const s of sources){if(!s.enabled)continue; try{if(s.type==='rss'){const feed=await this.withRetry(()=>this.parser.parseURL(s.url));for(const item of feed.items||[]){const n=this.normalize(item,s.name,{sourceType:'custom-rss'});if(this.isAllowed(n))out.push(n);}continue;} const r=await this.withRetry(()=>axios({method:s.method||'GET',url:s.url,headers:s.headers||{},params:s.params||{},timeout:20000})); if(this.tracker)this.tracker.trackHttp('custom',`news.fetch.${s.name||'source'}`); const items=getByPath(r.data,s.items_path||'items')||[]; for(const raw of items){const f=s.fields||{};const n=this.normalize({title:getByPath(raw,f.title||'title'),description:getByPath(raw,f.description||'description'),url:getByPath(raw,f.url||'url'),publishedAt:getByPath(raw,f.published_at||'publishedAt'),source:getByPath(raw,f.source||'source')},s.name,{sourceType:'custom-json'});if(this.isAllowed(n))out.push(n);}}catch(e){console.error(`[CUSTOM:${s.name}] ${e.message}`);}} return out; }
  async fetchAll(){ const [rss,api,custom]=await Promise.all([this.fetchRss(),this.fetchNewsApi(),this.fetchCustom()]); const all=[...rss,...api,...custom].filter(x=>Date.now()-new Date(x.publishedAt).getTime()<=(this.config.digest.lookback_hours||48)*3600*1000).sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt)); return dedupeBySimilarity(all,this.config.digest.dedup_similarity||.86); }
}
module.exports=NewsFetcher;
